server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  mail:
    host: 
    username: 
    password: 
    protocol: 
    port: 465
    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.auth: true
    default-encoding: utf-8




  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: 
    driver-class-name: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    time-zone: GMT+8

  redis:
    database: 0
    host: 
    port: 
    password: 
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    #session失效时间
  session:
    timeout: 86400




mybatis:
  type-aliases-package: com.j3ee.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


swagger:
  enable: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
